/*
  Portfolio projects. The order here is the order on the site.

  Add a project: copy an entry, change the fields, and put its images in
  assets/img/<slug>/ (cover-320.webp, cover-640.webp, cover-1280.webp,
  desktop.webp, desktop-960.webp, mobile.webp). tools/images.mjs builds all of
  them from any source image.

  category  bet-on | table | slots | betshop | sportsbook
  platform  online (desktop & mobile) | retail (betshop display) | web
  mobile    false when there is no mobile screen
  Text      a plain string is shown in every language (English source copy);
            { en, hy, ru } is translated. Simple HTML is allowed: <p> <ul> <li> <strong> <br> <em>.
*/
window.PROJECTS = [
  {
    slug: "hi-lo",
    name: "Hi Lo",
    category: "bet-on",
    platform: "online",
    company: "Pascal Gaming",
    role: "UX / UI / Interaction",
    coverAlt: "Big Hi Lo game artwork with playing cards",
    desktopAlt: "Final Hi Lo desktop design",
    mobileAlt: "Final mobile design with betting controls above navigation",
    link: {
      kind: "play",
      href: "https://pascalgaming.com/games/big-hilo",
    },
    summary: {
      en: "Making mobile betting controls easier to reach.",
      hy: "Ավելի հասանելի խաղադրույքի կառավարում բջջայինում։",
      ru: "Делаю управление ставками доступнее на мобильных устройствах.",
    },
    intro: {
      en: "A focused improvement to the live Hi Lo experience, making betting controls more accessible on mobile.",
      hy: "Hi Lo խաղի նպատակային բարելավում՝ բջջայինում խաղադրույքի կառավարումն ավելի հասանելի դարձնելու համար։",
      ru: "Точечное улучшение действующей игры Hi Lo: более доступное управление ставками на мобильных устройствах.",
    },
    problem: {
      en: "<p>Scrolling on mobile made betting controls difficult to access. Feedback from players and the product manager helped identify the issue.</p>",
      hy: "<p>Բջջայինում էջի սքրոլը դժվարացնում էր խաղադրույքի կառավարման հասանելիությունը։ Խաղացողների և պրոդուկտ մենեջերի արձագանքն օգնեց բացահայտել խնդիրը։</p>",
      ru: "<p>Прокрутка на мобильных устройствах затрудняла доступ к управлению ставками. Обратная связь игроков и продуктового менеджера помогла выявить проблему.</p>",
    },
    contribution: {
      en: "<p>I researched similar games and moved the betting controls to a more accessible position. I worked with the product manager and developers on the updated experience.</p>",
      hy: "<p>Ուսումնասիրեցի նմանատիպ խաղերը և խաղադրույքի կառավարումը տեղափոխեցի ավելի հասանելի դիրք։ Նոր փորձառության վրա աշխատեցի պրոդուկտ մենեջերի և ծրագրավորողների հետ։</p>",
      ru: "<p>Я изучил похожие игры и переместил управление ставками в более доступную область. Работал над обновлением вместе с продуктовым менеджером и разработчиками.</p>",
    },
    validation: {
      en: "<p>The design was reviewed with the product manager and tested with players. Players experienced fewer difficulties placing bets; no numerical performance claim is made.</p>",
      hy: "<p>Դիզայնը քննարկվեց պրոդուկտ մենեջերի հետ և փորձարկվեց խաղացողների կողմից։ Խաղադրույք կատարելիս նրանք ավելի քիչ դժվարությունների հանդիպեցին։</p>",
      ru: "<p>Дизайн прошёл обсуждение с продуктовым менеджером и тестирование с игроками. Игроки испытывали меньше трудностей при размещении ставок.</p>",
    },
  },
  {
    slug: "rockbet",
    name: "RockBet",
    category: "bet-on",
    genre: "Crash",
    platform: "online",
    company: "Pascal Gaming",
    role: "UX / UI",
    coverAlt: "RockBet game artwork",
    desktopAlt: "RockBet desktop design",
    mobileAlt: "RockBet mobile design",
    link: {
      kind: "play",
      href: "https://pascalgaming.com/games/rockbet",
    },
    summary: {
      en: "Dual betting controls for a fast-paced crash game.",
      hy: "Երկու խաղադրույքի կառավարում արագընթաց crash խաղում։",
      ru: "Управление двумя ставками в динамичной crash-игре.",
    },
    headline: {
      en: "Two bets.<br>One clear view.",
      hy: "Երկու խաղադրույք։<br>Մեկ հստակ տեսք։",
      ru: "Две ставки.<br>Один понятный экран.",
    },
    intro: {
      en: "A crash-game interface that brings two betting panels, the live multiplier and round history into one view.",
      hy: "Crash խաղի ինտերֆեյս՝ երկու խաղադրույքի վահանակով, ընթացիկ բազմապատկիչով և ռաունդների պատմությամբ։",
      ru: "Интерфейс crash-игры объединяет две панели ставок, текущий множитель и историю раундов.",
    },
    problem: {
      en: "<p>Players need to make quick decisions across two simultaneous bets without losing track of the multiplier or previous rounds.</p>",
      hy: "<p>Խաղացողները պետք է արագ որոշումներ կայացնեն երկու միաժամանակյա խաղադրույքի համար՝ հետևելով բազմապատկիչին ու նախորդ ռաունդներին։</p>",
      ru: "<p>Игрокам нужно быстро принимать решения по двум одновременным ставкам, не теряя из виду множитель и предыдущие раунды.</p>",
    },
    contribution: {
      en: "<p>I designed the dark UI, dual betting panels and manual and automatic cash-out controls. I gave the multiplier visual priority and organized live bets, round history and top wins in a sidebar, working with the product manager and developers.</p>",
      hy: "<p>Նախագծեցի մուգ ինտերֆեյսը, երկու խաղադրույքի վահանակները և ձեռքով ու ավտոմատ cash-out-ի կառավարումը։ Առանձնացրի բազմապատկիչը և կողային վահանակում կազմակերպեցի խաղադրույքները, պատմությունն ու խոշոր շահումները՝ աշխատելով պրոդուկտ մենեջերի և ծրագրավորողների հետ։</p>",
      ru: "<p>Я спроектировал тёмный интерфейс, две панели ставок и управление ручным и автоматическим выводом. Выделил множитель и организовал ставки, историю раундов и крупнейшие выигрыши в боковой панели совместно с продуктовым менеджером и разработчиками.</p>",
    },
    validation: {
      en: "<p>The design was reviewed with the product team and is now live.</p>",
      hy: "<p>Դիզայնը քննարկվել է պրոդուկտի թիմի հետ և այժմ գործում է։</p>",
      ru: "<p>Дизайн прошёл обсуждение с продуктовой командой и уже запущен.</p>",
    },
    validationLabel: "review",
  },
  {
    slug: "fighters",
    name: "Fighters",
    category: "bet-on",
    genre: "Crash",
    platform: "online",
    company: "Pascal Gaming",
    role: "UX / UI",
    coverAlt: "Fighters game artwork",
    desktopAlt: "Fighters desktop design",
    mobileAlt: "Fighters mobile design",
    link: {
      kind: "play",
      href: "https://pascalgaming.com/games/fighter-xxx",
    },
    summary: {
      en: "Clear betting decisions across three independent fighters.",
      hy: "Հստակ խաղադրույքներ երեք անկախ կործանիչների համար։",
      ru: "Понятные решения по ставкам на три независимых истребителя.",
    },
    headline: {
      en: "Multiple fighters.<br>Focused controls.",
      hy: "Մի քանի կործանիչ։<br>Հստակ կառավարում։",
      ru: "Несколько истребителей.<br>Понятное управление.",
    },
    intro: {
      en: "Fighter xXx features up to three fighters, each with an independent multiplier. The interface keeps selection, betting and live activity within one screen.",
      hy: "Fighter xXx-ում մինչև երեք կործանիչ ունեն անկախ բազմապատկիչներ։ Ընտրությունը, խաղադրույքներն ու ընթացիկ ակտիվությունը տեղավորվում են մեկ էկրանում։",
      ru: "В Fighter xXx до трёх истребителей имеют независимые множители. Выбор, ставки и активность игроков собраны на одном экране.",
    },
    problem: {
      en: "<p>Players need to manage multiple fighters within short countdown windows. Auto-bet, auto-cashout and quick controls must remain clear without crowding the game.</p>",
      hy: "<p>Խաղացողները պետք է կառավարեն մի քանի կործանիչ՝ կարճ հետհաշվարկի ընթացքում։ Ավտոմատ խաղադրույքը, cash-out-ը և արագ կառավարումը պետք է լինեն հասկանալի՝ առանց էկրանը ծանրաբեռնելու։</p>",
      ru: "<p>Игрокам нужно управлять несколькими истребителями за короткое время обратного отсчёта. Автоставки, автовывод и быстрые действия должны оставаться понятными и не перегружать игру.</p>",
    },
    contribution: {
      en: "<p>I designed the UI/UX, jet visuals, tabbed fighter selection and betting controls, including auto-bet, auto-cashout and quick multiplier buttons. I worked with the product manager and developers to integrate live bets and chat into the layout.</p>",
      hy: "<p>Նախագծեցի UI/UX-ը, կործանիչների վիզուալները, ներդիրներով ընտրությունն ու խաղադրույքի կառավարումը՝ ավտոմատ խաղադրույքով, cash-out-ով և արագ բազմապատկիչների կոճակներով։ Պրոդուկտ մենեջերի և ծրագրավորողների հետ ինտեգրեցի ընթացիկ խաղադրույքներն ու չատը։</p>",
      ru: "<p>Я спроектировал UI/UX, визуалы истребителей, выбор через вкладки и управление ставками: автоставки, автовывод и кнопки множителей. Вместе с продуктовым менеджером и разработчиками интегрировал текущие ставки и чат.</p>",
    },
    validation: {
      en: "<p>The design was reviewed with the product team and is now live.</p>",
      hy: "<p>Դիզայնը քննարկվել է պրոդուկտի թիմի հետ և այժմ գործում է։</p>",
      ru: "<p>Дизайн прошёл обсуждение с продуктовой командой и уже запущен.</p>",
    },
    validationLabel: "review",
  },
  {
    slug: "pixel-road",
    name: "Pixel Road",
    category: "bet-on",
    genre: "Instant",
    platform: "online",
    company: "Pascal Gaming",
    role: "UX / UI",
    coverAlt: "Pixel Road game artwork",
    desktopAlt: "Pixel Road desktop design",
    mobileAlt: "Pixel Road mobile design",
    link: {
      kind: "play",
      href: "https://www.ichancy.com/casino/slots/all/ICH/555575598-pixel-road?mode=fun",
    },
    intro: {
      en: "“Pixel Road” is a fast-paced game where the goal is to cross as many road lines as possible without encountering a car. The player can cash out their winnings at any stage of the game.",
      hy: "«Pixel Road»-ը արագընթաց խաղ է, որի նպատակն է անցնել ճանապարհի հնարավորինս շատ գոտիներ՝ առանց մեքենայի բախվելու։ Խաղացողը կարող է վերցնել իր շահումը խաղի ցանկացած փուլում։",
      ru: "«Pixel Road» — динамичная игра, в которой нужно пересечь как можно больше полос дороги, не столкнувшись с машиной. Игрок может забрать выигрыш на любом этапе игры.",
    },
    problem: {
      en: "<p>Arcade-style obstacle crossing games need to translate classic retro mechanics into a high-stakes risk-versus-reward betting experience. Players needed an intuitive way to adjust risk tiers dynamically (from casual to extreme) and make split-second lane choices without clunky UI overlays obstructing the pixel-art action.</p>",
      hy: "<p>Արգելքներ հաղթահարելու արկադային խաղերը պետք է դասական ռետրո մեխանիկաները վերածեն բարձր ռիսկի և հնարավոր շահույթի վրա հիմնված խաղադրույքային փորձառության։ Խաղացողներին անհրաժեշտ էր ռիսկի մակարդակները՝ պարզից մինչև ծայրահեղ, դինամիկ փոխելու և վայրկյանի մասերում գոտի ընտրելու հասկանալի եղանակ՝ առանց պիքսելային գործողությունը փակող ծանր ինտերֆեյսային շերտերի։</p>",
      ru: "<p>Аркадные игры с пересечением препятствий должны превращать классические ретромеханики в игровой опыт ставок с высоким риском и потенциальной наградой. Игрокам был нужен понятный способ динамически менять уровень риска — от простого до экстремального — и за доли секунды выбирать полосу, без громоздких элементов интерфейса, закрывающих пиксельную сцену.</p>",
    },
    contribution: {
      en: "<p>I designed the complete retro pixel-art UI/UX for this street-crossing hazard game, seamlessly blending core gaming mechanics with intuitive betting controls.</p>",
      hy: "<p>Ես նախագծել եմ վտանգավոր փողոցն անցնելու այս խաղի ամբողջական ռետրո պիքսելային UI/UX-ը՝ սահուն միավորելով հիմնական խաղային մեխանիկաները և խաղադրույքների հասկանալի կառավարումը։</p>",
      ru: "<p>Я спроектировал полный UI/UX в стиле ретро-пиксель-арта для этой игры о переходе опасной улицы, органично объединив основные игровые механики с понятным управлением ставками.</p>",
    },
    validation: {
      en: "<p>The interface was reviewed with the product team and validated through playtesting. The direct integration of bet multipliers onto the street lanes, paired with instant difficulty toggles, allowed players to easily build custom risk strategies, resulting in higher session duration and continuous round play.</p>",
      hy: "<p>Ինտերֆեյսը քննարկվել է պրոդուկտի թիմի հետ և ստուգվել խաղային փորձարկումներով։ Խաղադրույքի բազմապատկիչներն անմիջապես ճանապարհի գոտիներում տեղադրելը և բարդության ակնթարթային փոխարկիչները թույլ են տվել խաղացողներին հեշտությամբ կառուցել ռիսկի սեփական ռազմավարությունները։ Արդյունքում աճել է սեսիաների տևողությունը և ռաունդների շարունակական խաղը։</p>",
      ru: "<p>Интерфейс был рассмотрен продуктовой командой и проверен в игровых тестах. Прямое размещение множителей ставок на полосах дороги вместе с мгновенным переключением сложности позволило игрокам легко выстраивать собственные стратегии риска, что привело к увеличению длительности сессий и непрерывной игре раунд за раундом.</p>",
    },
  },
  {
    slug: "crash",
    name: "Crash",
    category: "bet-on",
    genre: "Crash",
    platform: "online",
    company: "Pascal Gaming",
    role: "UX / UI",
    coverAlt: "Crash game artwork",
    desktopAlt: "Crash desktop design",
    mobileAlt: "Crash mobile design",
    link: {
      kind: "play",
      href: "https://pascalgaming.com/games/crash",
    },
    intro: {
      en: "Crash is a classic, high-tension Instant Game where the multiplier climbs higher and higher until it crashes—test your nerves and cash out at the perfect moment!",
      hy: "Crash-ը դասական, լարված Instant Game է, որտեղ բազմապատկիչը բարձրանում է ավելի ու ավելի՝ մինչև կտրուկ անկումը։ Փորձեք ձեր համբերությունը և ճիշտ պահին վերցրեք շահումը։",
      ru: "Crash — классическая напряжённая Instant Game, в которой множитель растёт всё выше, пока не обрушится. Испытайте свою выдержку и заберите выигрыш в нужный момент!",
    },
    problem: {
      en: "<p>Players in crash games often struggle with two main issues: lack of transparency around game fairness and restrictive, single-bet interface layouts. To build long-term trust and cater to advanced players, the interface needed to combine verifiable fair-play data with a flexible, modular betting system—all within a fast-moving, continuous game cycle.</p>",
      hy: "<p>Crash խաղերի խաղացողները հաճախ բախվում են երկու հիմնական խնդրի՝ խաղի արդարության ոչ բավարար թափանցիկություն և մեկ խաղադրույքով սահմանափակող ինտերֆեյսներ։ Երկարաժամկետ վստահություն ձևավորելու և փորձառու խաղացողների կարիքները բավարարելու համար ինտերֆեյսը պետք է միավորեր արդար խաղի ստուգելի տվյալներն ու խաղադրույքների ճկուն, մոդուլային համակարգը՝ արագ ընթացող, շարունակական խաղային ցիկլի մեջ։</p>",
      ru: "<p>Игроки в crash-игры часто сталкиваются с двумя основными проблемами: недостаточной прозрачностью честности игры и ограничивающими интерфейсами с одной ставкой. Чтобы создать долгосрочное доверие и учесть потребности опытных игроков, интерфейс должен был объединить проверяемые данные о честной игре с гибкой модульной системой ставок в рамках быстрого непрерывного игрового цикла.</p>",
    },
    contribution: {
      en: "<p>I designed the complete dark-mode UI/UX for this “1 Crash” game with a heavy focus on transparency and user customization.</p>",
      hy: "<p>Ես նախագծել եմ «1 Crash» խաղի ամբողջական մուգ թեմայով UI/UX-ը՝ շեշտը դնելով թափանցիկության և օգտատիրոջ կողմից անհատականացման վրա։</p>",
      ru: "<p>Я спроектировал полный UI/UX в тёмной теме для игры «1 Crash», сделав основной акцент на прозрачности и пользовательской настройке.</p>",
    },
    validation: {
      en: "<p>The design was reviewed with product stakeholders and validated through user testing. Players reported high confidence due to the visible Provably Fair verification system, and the modular Create New bet slip feature made executing multi-bet strategies effortless during fast round transitions.</p>",
      hy: "<p>Դիզայնը քննարկվել է պրոդուկտի շահագրգիռ կողմերի հետ և ստուգվել օգտատերերի փորձարկումներով։ Խաղացողները նշել են բարձր վստահություն՝ տեսանելի Provably Fair ստուգման համակարգի շնորհիվ։ Խաղադրույքի նոր կտրոն ավելացնելու մոդուլային Create New գործառույթը հեշտացրել է մի քանի խաղադրույքով ռազմավարությունների իրականացումը՝ ռաունդների արագ անցումների ընթացքում։</p>",
      ru: "<p>Дизайн был рассмотрен заинтересованными сторонами продукта и проверен в пользовательских тестах. Игроки сообщили о высокой уверенности благодаря видимой системе проверки Provably Fair, а модульная функция добавления купона ставки Create New позволила легко выполнять стратегии с несколькими ставками во время быстрых переходов между раундами.</p>",
    },
  },
  {
    slug: "tornado-roulette",
    name: "Tornado Roulette",
    category: "table",
    platform: "online",
    company: "Pascal Gaming",
    role: "UX / UI",
    coverAlt: "Tornado Roulette game artwork",
    desktopAlt: "Tornado Roulette desktop design",
    mobileAlt: "Tornado Roulette mobile design",
    link: {
      kind: "play",
      href: "https://pascalgaming.com/games/tornado-roulette-2",
    },
    intro: {
      en: "Tornado Roulette unleashes a whirlwind of massive wins with the Tornado Booster Multiplier delivering jaw-dropping odds from x50 to an incredible x700 on every spin!",
      hy: "Tornado Roulette-ը բերում է խոշոր շահումների հորձանուտ․ Tornado Booster բազմապատկիչը յուրաքանչյուր պտույտում առաջարկում է x50-ից մինչև անհավանական x700 գործակիցներ։",
      ru: "Tornado Roulette открывает вихрь крупных выигрышей: множитель Tornado Booster предлагает коэффициенты от x50 до невероятных x700 в каждом вращении!",
    },
    problem: {
      en: "<p>Roulette players—especially experienced ones—need immediate access to both standard table bets and advanced call/neighbor bets (racetrack) without losing sight of the live 3D wheel or being overwhelmed by stacked menus during short betting windows.</p>",
      hy: "<p>Ռուլետկայի խաղացողներին, հատկապես փորձառուներին, անհրաժեշտ է անմիջական հասանելիություն ինչպես սեղանի ստանդարտ խաղադրույքներին, այնպես էլ բարդ հայտարարված և հարևան թվերի խաղադրույքներին (racetrack)։ Միաժամանակ նրանք պետք է տեսնեն գործող 3D անիվը և չծանրաբեռնվեն բազմաշերտ մենյուներով՝ խաղադրույքների համար հատկացված կարճ ժամանակահատվածում։</p>",
      ru: "<p>Игрокам в рулетку, особенно опытным, нужен мгновенный доступ как к стандартным ставкам на столе, так и к сложным объявленным ставкам и ставкам на соседние номера (racetrack). При этом они не должны терять из виду живое 3D-колесо или путаться в многоуровневых меню во время короткого приёма ставок.</p>",
    },
    contribution: {
      en: "<p>I designed the complete end-to-end UI/UX for “Tornado Roulette,” balancing a high-end luxury casino visual style with an ergonomic betting hierarchy.</p>",
      hy: "<p>Ես նախագծել եմ «Tornado Roulette»-ի ամբողջական UI/UX-ը՝ համադրելով պրեմիում խաղատան վիզուալ ոճը և խաղադրույքների կառավարման հարմար հիերարխիան։</p>",
      ru: "<p>Я спроектировал полный UI/UX для «Tornado Roulette», объединив визуальный стиль премиального казино с удобной иерархией управления ставками.</p>",
    },
    validation: {
      en: "<p>The interface was reviewed with product stakeholders and tested with casino game players. Having the racetrack and main board available simultaneously on one screen enabled players to place complex combination bets faster and with fewer misclicks during high-tempo rounds.</p>",
      hy: "<p>Ինտերֆեյսը քննարկվել է պրոդուկտի շահագրգիռ կողմերի հետ և փորձարկվել խաղատան խաղացողների մասնակցությամբ։ Racetrack-ի և հիմնական դաշտի միաժամանակյա հասանելիությունը մեկ էկրանին թույլ է տվել խաղացողներին արագ տեղադրել բարդ համակցված խաղադրույքներ և ավելի քիչ սխալ սեղմումներ կատարել արագ ընթացող ռաունդների ժամանակ։</p>",
      ru: "<p>Интерфейс был рассмотрен заинтересованными сторонами продукта и протестирован с игроками казино. Одновременная доступность racetrack и основного поля на одном экране позволила игрокам быстрее размещать сложные комбинированные ставки и реже нажимать не туда во время динамичных раундов.</p>",
    },
  },
  {
    slug: "bet-on-poker",
    name: "Bet On Poker",
    category: "table",
    platform: "online",
    company: "Pascal Gaming",
    role: "UX / UI",
    coverAlt: "Bet On Poker game artwork",
    desktopAlt: "Bet On Poker desktop design",
    mobileAlt: "Bet On Poker mobile design",
    link: {
      kind: "play",
      href: "https://pascalgaming.com/games/bet-on-poker",
    },
    intro: {
      en: "Bet on Poker reimagines the classic card showdown as an unlimited-player betting spectacle—predict winning hands, combinations, and side markets across four thrilling stages with shifting odds!",
      hy: "Bet on Poker-ը դասական քարտային մրցակցությունը վերածում է անսահմանափակ թվով խաղացողների համար խաղադրույքային ներկայացման․ կանխատեսեք հաղթող ձեռքերը, համակցություններն ու լրացուցիչ ելքերը՝ փոփոխվող գործակիցներով չորս հետաքրքիր փուլերի ընթացքում։",
      ru: "Bet on Poker переосмысляет классическое карточное противостояние как зрелище со ставками для неограниченного числа игроков: предсказывайте выигрышные руки, комбинации и дополнительные исходы на четырёх захватывающих этапах с меняющимися коэффициентами!",
    },
    problem: {
      en: "<p>Multi-hand live poker betting games can quickly become visually overwhelming when tracking multiple hand positions, changing odds, and chip placements simultaneously. Players needed a clear, real-time view of six distinct hand positions and community cards, alongside fast chip controls to make multi-position bets before time ran out.</p>",
      hy: "<p>Մի քանի պոկերային ձեռքերի վրա իրական ժամանակում խաղադրույքներ կատարելու խաղերը կարող են արագ դառնալ տեսողականորեն ծանրաբեռնված, երբ միաժամանակ պետք է հետևել ձեռքերի դիրքերին, փոփոխվող գործակիցներին և չիփերի տեղադրմանը։ Խաղացողներին անհրաժեշտ էր վեց առանձին ձեռքերի դիրքերի և ընդհանուր քարտերի հստակ տեսք իրական ժամանակում, ինչպես նաև չիփերի արագ կառավարում՝ մինչև ժամանակի ավարտը մի քանի դիրքերի վրա խաղադրույքներ կատարելու համար։</p>",
      ru: "<p>Игры со ставками на несколько покерных рук в реальном времени быстро становятся визуально перегруженными: нужно одновременно отслеживать несколько позиций, меняющиеся коэффициенты и размещение фишек. Игрокам требовался понятный обзор шести отдельных позиций рук и общих карт в реальном времени, а также быстрое управление фишками для размещения ставок на несколько позиций до окончания времени.</p>",
    },
    contribution: {
      en: "<p>I designed the full digital table interface for “Bet On Poker,” focusing on realistic table aesthetics combined with high-clarity betting UX.</p>",
      hy: "<p>Ես նախագծել եմ «Bet On Poker»-ի ամբողջ թվային սեղանի ինտերֆեյսը՝ կենտրոնանալով սեղանի իրատեսական գեղագիտության և խաղադրույքների առավելագույնս հստակ UX-ի համադրության վրա։</p>",
      ru: "<p>Я спроектировал весь интерфейс цифрового стола для «Bet On Poker», уделив особое внимание реалистичной эстетике стола и максимально понятному UX ставок.</p>",
    },
    validation: {
      en: "<p>The design was reviewed with product stakeholders and tested with target players. The intuitive visual feedback on hand status (clear Win/Loss indicators) and the streamlined chip placement flow reduced user errors during live dealing phases and encouraged higher multi-position bet placement.</p>",
      hy: "<p>Դիզայնը քննարկվել է պրոդուկտի շահագրգիռ կողմերի հետ և փորձարկվել թիրախային խաղացողների մասնակցությամբ։ Ձեռքերի վիճակի հասկանալի վիզուալ արձագանքը՝ հաղթանակի ու պարտության հստակ ցուցիչներով, և չիփերի տեղադրման պարզեցված հոսքը նվազեցրել են օգտատերերի սխալները քարտերի բաժանման ընթացքում և խրախուսել մի քանի դիրքերի վրա ավելի շատ խաղադրույքների տեղադրումը։</p>",
      ru: "<p>Дизайн был рассмотрен заинтересованными сторонами продукта и протестирован с целевыми игроками. Понятная визуальная обратная связь о состоянии рук — чёткие индикаторы выигрыша и проигрыша — и упрощённый процесс размещения фишек сократили ошибки пользователей во время раздачи и способствовали увеличению ставок на несколько позиций.</p>",
    },
  },
  {
    slug: "golden-tree-buy-bonus",
    name: "Golden Tree Buy Bonus",
    category: "slots",
    platform: "online",
    company: "Pascal Gaming",
    role: "UX / UI",
    coverAlt: "Golden Tree Buy Bonus game artwork",
    desktopAlt: "Golden Tree Buy Bonus desktop design",
    mobileAlt: "Golden Tree Buy Bonus mobile design",
    link: {
      kind: "play",
      href: "https://pascalgaming.com/games/golden-tree-20-000-buy-bonus",
    },
    intro: "Golden Tree 100: Buy Bonus bursts with vibrant colors and 100 winning lines, where customizable wild buys and x1-x5 multipliers fuel epic x10,000 payouts!",
    problem: "<p>Classic slot games require a standardized, highly ergonomic betting UI and modal workflow that can function seamlessly across an entire suite of titles without re-engineering core controls for every new release. The challenge was to design a mobile-first betting architecture, including complex popup interfaces like Bonus Buy options and win celebrations, that ensures high visual clarity, one-handed usability, and brand consistency.</p>",
    contribution: "<p>I designed the complete UI/UX framework for the entire betting interface, buttons, control bars, and popup modal systems (excluding the individual game symbols). Notably, this betting layout was designed as a core reusable component utilized across similar classic slot games in our product portfolio. Key highlights include:</p><ul><li><strong>Core Betting Dock &amp; Controls</strong> Engineered the main spin button, bet level modifiers, last-win display, and fast-action toggles (Turbo, Auto-spin, settings drawer) optimized for thumb navigation on mobile devices.</li><li><strong>Buy Bonus Modal System</strong> Designed the full overlay flow where players can browse different bonus tiers, preview wild counts, dynamically adjust purchase stakes using direct + / - controls, and confirm transactions via a prominent BUY action button.</li><li><strong>Win Announcement &amp; Congratulatory Popups</strong> Created high-impact modal dialogs for reward triggers, bonus start screens, and win summaries to maintain visual excitement.</li><li><strong>Modular Design Architecture</strong> Built the entire betting interface and popup framework as a flexible UI system that can be seamlessly applied to other classic slot games, ensuring consistency across the catalog.</li></ul>",
    validation: "<p>The framework was reviewed with product stakeholders and deployed across multiple classic titles. Standardizing the core betting interface and popup UX dramatically reduced player friction when switching between games, while the clean “Buy Bonus” modal design led to higher feature adoption and smoother overall session flow.</p>",
  },
  {
    slug: "sugar-balloon",
    name: "Sugar Balloon",
    category: "slots",
    platform: "online",
    company: "Pascal Gaming",
    role: "UX / UI",
    coverAlt: "Sugar Balloon game artwork",
    desktopAlt: "Sugar Balloon desktop design",
    mobileAlt: "Sugar Balloon mobile design",
    link: {
      kind: "play",
      href: "https://pascalgaming.com/games/sugar-balloon",
    },
    intro: "“Sugar Balloon” is a candy-themed scatter-pay / cascading slot game featuring vibrant sweet-themed visuals, dynamic multipliers, and advanced feature-buy options. The game offers players enhanced tactical control through special side-bet modes—such as “Double Chance,” “Random Bet,” and “Boosted Bet”—allowing them to customize gameplay volatility and bonus triggers.",
    problem: "<p>Complex slot games with multiple side-bet mechanisms and variable multiplier tiers can easily confuse players if the option cards and stake inputs are not structured intuitively. The challenge was to create a mobile and web-responsive modal system that presents high-stake choices clearly, prevents accidental triggers, and seamlessly integrates dynamic multiplier selection without cluttering the main game view.</p>",
    contribution: "<p>I designed the complete UI/UX framework for the betting interface, popup modal systems, buttons, and control bars (excluding the individual reel game symbols). Notably, this betting architecture was engineered as a core reusable component utilized across similar bonus-heavy slot games in our product portfolio. Key highlights include:</p><ul><li><strong>Special Bets Modal System</strong> Designed the main interactive overlay featuring distinct, color-coded option cards (“Double Chance”, “Random Bet”, and “Boosted Bet”) with clear feature descriptions, dynamic stake controls (- / +), and a prominent ACTIVATE Call-to-Action button.</li><li><strong>Complete Multiplier Design &amp; Selectors</strong> Designed all multiplier visual elements, badges, and interactive modifier controls (such as the x2 boosted multiplier selectors) to make multiplier states instantly readable across all screen sizes.</li><li><strong>Side-Bet Entry Triggers</strong> Created high-visibility side buttons for “BUY BONUS” and “SPECIAL BETS” on the main game interface for effortless one-click access to feature overlays.</li><li><strong>Core Reusable Betting Dock</strong> Built the entire bottom navigation panel—including the main spin button, balance tracking, last win display, bet adjustments, and fast toggles (Turbo, Auto-spin)—as a standardized core component reused across similar bonus-driven titles.</li></ul>",
    validation: "<p>The design was reviewed with product managers and validated through user testing across multiple game releases. The intuitive breakdown of feature cards and explicit multiplier controls resulted in higher engagement with “Special Bets” modes, while the reusable core UI significantly streamlined development time and ensured UX consistency across all similar titles.</p>",
  },
  {
    slug: "juicy-storm",
    name: "Juicy Storm",
    category: "slots",
    platform: "online",
    company: "Pascal Gaming",
    role: "UX / UI",
    coverAlt: "Juicy Storm game artwork",
    desktopAlt: "Juicy Storm desktop design",
    mobileAlt: "Juicy Storm mobile design",
    link: {
      kind: "play",
      href: "https://pascal-pre-live-18754649.springbuilder.site/video-slots/slots/all/51/pascal-gaming/88535-555558647-juicy-storm?mode=fun",
    },
    intro: "“Juicy Storm” is a vibrant, fruit- and sugar-themed 6x5 video slot game featuring a Pay Anywhere payout engine and cascading reels. Built for high-volatility action, the game includes explosive win multipliers, a “Double Chance” side-bet toggle to double bonus trigger odds, and direct “Buy Bonus” overlays for instant free spin access.",
    problem: "<p>High-tempo scatter-pay slots with cascading reels and dynamic multipliers require a streamlined betting interface and popup workflow that keeps complex choices simple. The challenge was to design a mobile- and web-responsive betting architecture—including feature purchase popups, multiplier indicators, and side-bet toggles—that delivers crisp visual hierarchy, prevents accidental clicks, and serves as a scalable component framework across diverse slot titles.</p>",
    contribution: "<p>I designed the complete UI/UX framework for the betting interface, control buttons, popup modal systems, and all visual multipliers (excluding the individual reel game symbols). Notably, this betting architecture was engineered as a core reusable component utilized across similar bonus-heavy slot games in our product portfolio. Key highlights include:</p><ul><li><strong>Core Reusable Betting Dock</strong> Engineered the main control bar—including the primary spin button, direct stake adjusters (- / +), bet amount readout, last-win tracker, balance display, and quick-action toggles (Turbo, Auto-spin, settings drawer)—as a standardized core component reused across similar slot titles.</li><li><strong>“Buy Bonus” &amp; Feature Popups</strong> Designed the interactive purchase overlays for instant bonus round activation, complete with clear cost previews, confirmation steps, and themed modal containers.</li><li><strong>“Double Chance” &amp; Side-Bet UI Elements</strong> Created intuitive toggle buttons and badges for side-bet options (such as “Double Chance”), allowing players to modify their bonus trigger odds effortlessly from the main interface.</li><li><strong>Complete Multipliers &amp; Visual UI Elements</strong> Designed all multiplier UI badges, numerical indicators, button states, and popup dialogs across both the base game and bonus rounds, ensuring immediate visual clarity during high-multiplier cascading wins.</li></ul>",
    validation: "<p>The framework was reviewed with product stakeholders and deployed across multiple slot titles. Standardizing this core betting engine across similar games drastically reduced development deployment time, while the intuitive breakdown of feature popups and explicit multiplier controls resulted in higher feature adoption and smoother overall session flow.</p>",
  },
  {
    slug: "fortune-master-goat",
    name: "Fortune Master Goat",
    category: "slots",
    platform: "online",
    company: "Pascal Gaming",
    role: "UX / UI",
    coverAlt: "Fortune Master Goat game artwork",
    desktopAlt: "Fortune Master Goat desktop design",
    mobileAlt: "Fortune Master Goat mobile design",
    link: {
      kind: "play",
      href: "https://pascalgaming.com/games/fortune-master-goat",
    },
    intro: "“Fortune Master Goat” is an Asian-themed video slot game built around fortune mechanics, dynamic win multipliers, bonus feature triggers, and an instant “Buy Bonus” option that grants players direct access to high-volatility free spin rounds.",
    problem: "<p>Theme-driven slot games require an ergonomic, standardized betting UI and modal workflow that can function seamlessly across an entire portfolio without re-engineering core controls for every new title release. The challenge was to design a mobile- and web-responsive betting architecture—including complex popup interfaces, multiplier badges, and feature buy overlays—that ensures high visual clarity, one-handed usability, and brand consistency across diverse game themes.</p>",
    contribution: "<p>I designed the complete UI/UX framework for the betting interface, control buttons, jackpot/bonus HUDs, popup modal systems, and all visual multipliers (excluding the individual reel game symbols). Notably, this betting architecture was engineered as a core reusable component utilized across similar slot games in our product portfolio. Key highlights include:</p><ul><li><strong>Core Reusable Betting Dock</strong> Engineered the main control bar—including the primary spin button, direct stake adjusters (- / +), bet amount readout, last-win tracker, balance display, and quick-action toggles (Turbo, Auto-spin, settings drawer)—as a standardized core component reused across similar slot titles.</li><li><strong>Themed “Buy Bonus” Access &amp; Modals</strong> Created the integrated “BUY BONUS” side button with live cost calculation alongside the full popup overlay system for feature purchases and bonus round confirmations.</li><li><strong>Feature HUD &amp; Popup Modals</strong> Structured win celebration popups, feature trigger dialogs, and bonus selection overlays to deliver clear, high-contrast visual updates during active gameplay transitions.</li><li><strong>Complete Multiplier &amp; UI Element Design</strong> Designed all multiplier UI badges, numeric indicators, buttons, and popup dialogs across the game, maintaining crisp visual hierarchy and immediate player feedback during feature triggers and boosted wins.</li></ul>",
    validation: "<p>The framework was reviewed with product stakeholders and deployed across multiple slot titles. Standardizing this core betting engine across similar games drastically reduced development deployment time, while the intuitive breakdown of feature cards and explicit multiplier controls resulted in higher feature adoption and smoother overall session flow.</p>",
  },
  {
    slug: "fortune-don-tiger",
    name: "Fortune Don Tiger",
    category: "slots",
    platform: "online",
    company: "Pascal Gaming",
    role: "UX / UI",
    coverAlt: "Fortune Don Tiger game artwork",
    desktopAlt: "Fortune Don Tiger desktop design",
    mobileAlt: "Fortune Don Tiger mobile design",
    link: {
      kind: "play",
      href: "https://pascalgaming.com/game-portfolio",
    },
    intro: "“Fortune Don Tiger” is a luxurious Asian-themed slot game filled with golden prosperity, featuring the mighty Tiger Don character, classic 5x3 grid layout, dynamic bonus game triggers, and fortune-multiplying mechanics designed to deliver balanced wins and steady excitement.",
    problem: "<p>Theme-driven slot games require an ergonomic, standardized betting UI and modal workflow that can function seamlessly across an entire portfolio without re-engineering core controls for every new title release. The challenge was to design a mobile- and web-responsive betting architecture—including complex popup interfaces, multiplier badges, and feature buy overlays—that ensures high visual clarity, one-handed usability, and brand consistency across diverse game themes.</p>",
    contribution: "<p>I designed the complete UI/UX framework for the betting interface, control buttons, jackpot/bonus HUDs, popup modal systems, and all visual multipliers (excluding the individual reel game symbols). Notably, this betting architecture was engineered as a core reusable component utilized across similar slot games in our product portfolio. Key highlights include:</p><ul><li><strong>Core Reusable Betting Dock</strong> Engineered the main control bar—including the primary spin button, direct stake adjusters (- / +), bet amount readout, last-win tracker, balance display, and quick-action toggles (Turbo, Auto-spin, settings drawer)—as a standardized core component reused across similar slot titles.</li><li><strong>Themed “Buy Bonus” Access &amp; Modals</strong> Created the integrated “BUY BONUS” side button with live cost calculation alongside the full popup overlay system for feature purchases and bonus round confirmations.</li><li><strong>Feature HUD &amp; Popup Modals</strong> Structured win celebration popups, feature trigger dialogs, and bonus selection overlays to deliver clear, high-contrast visual updates during active gameplay transitions.</li><li><strong>Complete Multiplier &amp; UI Element Design</strong> Designed all multiplier UI badges, numeric indicators, buttons, and popup dialogs across the game, maintaining crisp visual hierarchy and immediate player feedback during feature triggers and boosted wins.</li></ul>",
    validation: "<p>The framework was reviewed with product stakeholders and deployed across multiple slot titles. Standardizing this core betting engine across similar games drastically reduced development deployment time, while the intuitive breakdown of feature cards and explicit multiplier controls resulted in higher feature adoption and smoother overall session flow.</p>",
  },
  {
    slug: "fortune-capinho",
    name: "Fortune Capinho",
    category: "slots",
    platform: "online",
    company: "Pascal Gaming",
    role: "UX / UI",
    coverAlt: "Fortune Capinho game artwork",
    desktopAlt: "Fortune Capinho desktop design",
    mobileAlt: "Fortune Capinho mobile design",
    link: {
      kind: "play",
      href: "https://pascalgaming.com/games/fortune-capinho",
    },
    intro: "“Fortune Capinho” is a capybara-themed 3-reel slot game that combines charm with fortune mechanics. It features dynamic bonus rounds, reel respin features, hold mechanics, and multiplier boosts, offering balanced medium-volatility gameplay designed for fast-paced mobile and desktop action.",
    problem: "<p>Theme-driven slot games require an ergonomic, standardized betting UI and modal workflow that can function seamlessly across an entire portfolio without re-engineering core controls for every new title release. The challenge was to design a mobile- and web-responsive betting architecture—including complex popup interfaces, multiplier badges, and feature buy overlays—that ensures high visual clarity, one-handed usability, and brand consistency across diverse game themes.</p>",
    contribution: "<p>I designed the complete UI/UX framework for the betting interface, control buttons, jackpot/bonus HUDs, popup modal systems, and all visual multipliers (excluding the individual reel game symbols). Notably, this betting architecture was engineered as a core reusable component utilized across similar slot games in our product portfolio. Key highlights include:</p><ul><li><strong>Core Reusable Betting Dock</strong> Engineered the main control bar—including the primary spin button, direct stake adjusters (- / +), bet amount readout, last-win tracker, balance display, and quick-action toggles (Turbo, Auto-spin, settings drawer)—as a standardized core component reused across similar slot titles.</li><li><strong>Themed “Buy Bonus” Access &amp; Modals</strong> Created the integrated “BUY BONUS” side button with live cost calculation alongside the full popup overlay system for feature purchases and bonus round confirmations.</li><li><strong>Feature HUD &amp; Popup Modals</strong> Structured win celebration popups, feature trigger dialogs, respin indicators, and bonus selection overlays to deliver clear, high-contrast visual updates during active gameplay transitions.</li><li><strong>Complete Multiplier &amp; UI Element Design</strong> Designed all multiplier UI badges, numeric indicators, buttons, and popup dialogs across the game, maintaining crisp visual hierarchy and immediate player feedback during feature triggers and boosted wins.</li></ul>",
    validation: "<p>The framework was reviewed with product stakeholders and deployed across multiple slot titles. Standardizing this core betting engine across similar games drastically reduced development deployment time, while the intuitive breakdown of feature cards and explicit multiplier controls resulted in higher feature adoption and smoother overall session flow.</p>",
  },
  {
    slug: "fortune-ronaldinho",
    name: "Fortune Ronaldinho",
    category: "slots",
    platform: "online",
    company: "Pascal Gaming",
    role: "UX / UI",
    coverAlt: "Fortune Ronaldinho game artwork",
    desktopAlt: "Fortune Ronaldinho desktop design",
    mobileAlt: "Fortune Ronaldinho mobile design",
    link: {
      kind: "play",
      href: "https://pascalgaming.com/games/fortune-ronaldinho",
    },
    intro: "“Fortune Ronaldinho” is an official slot collaboration with football legend Ronaldinho. Featuring a unique 3-4-3 reel layout, the game blends sports excitement with high-reward slot mechanics, offering dynamic prize symbols delivering payouts up to 500x, a randomly triggered “Ronaldinho Feature” granting 8 Fortune Spins, and up to a 5,000x max win multiplier.",
    problem: "<p>Branded and theme-driven slot games require an ergonomic, standardized betting UI and modal workflow that can function seamlessly across an entire portfolio without re-engineering core controls for every new title release. The challenge was to design a mobile- and web-responsive betting architecture—including complex popup interfaces, multiplier badges, and feature overlays—that ensures high visual clarity, one-handed usability, and brand consistency across diverse game themes.</p>",
    contribution: "<p>I designed the complete UI/UX framework for the betting interface, control buttons, jackpot/bonus HUDs, popup modal systems, and all visual multipliers (excluding the individual reel game symbols). Notably, this betting architecture was engineered as a core reusable component utilized across similar slot games in our product portfolio. Key highlights include:</p><ul><li><strong>Core Reusable Betting Dock</strong> Engineered the main control bar—including the primary spin button, direct stake adjusters (- / +), bet amount readout, last-win tracker, balance display, and quick-action toggles (Turbo, Auto-spin, settings drawer)—as a standardized core component reused across similar slot titles.</li><li><strong>Themed Feature Access &amp; Modals</strong> Created integrated feature side buttons with live cost calculations alongside full popup overlay systems for feature purchases, bonus round confirmations, and special spin modes.</li><li><strong>Feature HUD &amp; Popup Modals</strong> Structured win celebration popups, feature trigger dialogs (such as the 8 Fortune Spins activation), and prize symbol indicators to deliver clear, high-contrast visual updates during active gameplay transitions.</li><li><strong>Complete Multiplier &amp; UI Element Design</strong> Designed all multiplier UI badges, numeric indicators, buttons, and popup dialogs across the game, maintaining crisp visual hierarchy and immediate player feedback during feature triggers and boosted wins.</li></ul>",
    validation: "<p>The framework was reviewed with product stakeholders and deployed across multiple slot titles. Standardizing this core betting engine across similar games drastically reduced development deployment time, while the intuitive breakdown of feature cards and explicit multiplier controls resulted in higher feature adoption and smoother overall session flow.</p>",
  },
  {
    slug: "fortune-tao-panda",
    name: "Fortune Tao Panda",
    category: "slots",
    platform: "online",
    company: "Pascal Gaming",
    role: "UX / UI",
    coverAlt: "Fortune Tao Panda game artwork",
    desktopAlt: "Fortune Tao Panda desktop design",
    mobileAlt: "Fortune Tao Panda mobile design",
    link: {
      kind: "play",
      href: "https://pascalgaming.com/games/fortune-tao-panda",
    },
    intro: "“Fortune Tao Panda” is an Asian- and nature-themed slot game featuring the wise Tao Panda, active Wild symbols, scatter-triggered free spin bonus rounds, dynamic win multiplier boosts, and an instant “Buy Bonus” option allowing players to directly trigger high-reward free spin rounds.",
    problem: "<p>Theme-driven slot games require an ergonomic, standardized betting UI and modal workflow that can function seamlessly across an entire portfolio without re-engineering core controls for every new title release. The challenge was to design a mobile- and web-responsive betting architecture—including complex popup interfaces, multiplier badges, and feature buy overlays—that ensures high visual clarity, one-handed usability, and brand consistency across diverse game themes.</p>",
    contribution: "<p>I designed the complete UI/UX framework for the betting interface, control buttons, jackpot/bonus HUDs, popup modal systems, and all visual multipliers (excluding the individual reel game symbols). Notably, this betting architecture was engineered as a core reusable component utilized across similar slot games in our product portfolio. Key highlights include:</p><ul><li><strong>Core Reusable Betting Dock</strong> Engineered the main control bar—including the primary spin button, direct stake adjusters (- / +), bet amount readout, last-win tracker, balance display, and quick-action toggles (Turbo, Auto-spin, settings drawer)—as a standardized core component reused across similar slot titles.</li><li><strong>Themed “Buy Bonus” Access &amp; Modals</strong> Created the integrated “BUY BONUS” side button with live cost calculation alongside the full popup overlay system for feature purchases and bonus round confirmations.</li><li><strong>Feature HUD &amp; Popup Modals</strong> Structured win celebration popups, feature trigger dialogs, and bonus selection overlays to deliver clear, high-contrast visual updates during active gameplay transitions.</li><li><strong>Complete Multiplier &amp; UI Element Design</strong> Designed all multiplier UI badges, numeric indicators, buttons, and popup dialogs across the game, maintaining crisp visual hierarchy and immediate player feedback during feature triggers and boosted wins.</li></ul>",
    validation: "<p>The framework was reviewed with product stakeholders and deployed across multiple slot titles. Standardizing this core betting engine across similar games drastically reduced development deployment time, while the intuitive breakdown of feature cards and explicit multiplier controls resulted in higher feature adoption and smoother overall session flow.</p>",
  },
  {
    slug: "fortune-calico",
    name: "Fortune Calico",
    category: "slots",
    platform: "online",
    company: "Pascal Gaming",
    role: "UX / UI",
    coverAlt: "Fortune Calico game artwork",
    desktopAlt: "Fortune Calico desktop design",
    mobileAlt: "Fortune Calico mobile design",
    link: {
      kind: "play",
      href: "https://pascalgaming.com/games/fortune-calico",
    },
    intro: "“Fortune Calico” is a vibrant feline- and fortune-themed slot game centered around the cool Calico cat. Featuring colorful visuals, dynamic win multiplier boosts, bonus spin triggers, and an instant “Buy Bonus” option, the game offers high-energy slot mechanics designed for smooth mobile and desktop play.",
    problem: "<p>Theme-driven slot games require an ergonomic, standardized betting UI and modal workflow that can function seamlessly across an entire portfolio without re-engineering core controls for every new title release. The challenge was to design a mobile- and web-responsive betting architecture—including complex popup interfaces, multiplier badges, and feature buy overlays—that ensures high visual clarity, one-handed usability, and brand consistency across diverse game themes.</p>",
    contribution: "<p>I designed the complete UI/UX framework for the betting interface, control buttons, jackpot/bonus HUDs, popup modal systems, and all visual multipliers (excluding the individual reel game symbols). Notably, this betting architecture was engineered as a core reusable component utilized across similar slot games in our product portfolio. Key highlights include:</p><ul><li><strong>Core Reusable Betting Dock</strong> Engineered the main control bar—including the primary spin button, direct stake adjusters (- / +), bet amount readout, last-win tracker, balance display, and quick-action toggles (Turbo, Auto-spin, settings drawer)—as a standardized core component reused across similar slot titles.</li><li><strong>Themed “Buy Bonus” Access &amp; Modals</strong> Created the integrated “BUY BONUS” side button with live cost calculation alongside the full popup overlay system for feature purchases and bonus round confirmations.</li><li><strong>Feature HUD &amp; Popup Modals</strong> Structured win celebration popups, feature trigger dialogs, respin indicators, and bonus selection overlays to deliver clear, high-contrast visual updates during active gameplay transitions.</li><li><strong>Complete Multiplier &amp; UI Element Design</strong> Designed all multiplier UI badges, numeric indicators, buttons, and popup dialogs across the game, maintaining crisp visual hierarchy and immediate player feedback during feature triggers and boosted wins.</li></ul>",
    validation: "<p>The framework was reviewed with product stakeholders and deployed across multiple slot titles. Standardizing this core betting engine across similar games drastically reduced development deployment time, while the intuitive breakdown of feature cards and explicit multiplier controls resulted in higher feature adoption and smoother overall session flow.</p>",
  },
  {
    slug: "fortune-pots",
    name: "Fortune Pots",
    category: "slots",
    platform: "online",
    company: "Pascal Gaming",
    role: "UX / UI",
    coverAlt: "Fortune Pots game artwork",
    desktopAlt: "Fortune Pots desktop design",
    mobileAlt: "Fortune Pots mobile design",
    link: {
      kind: "play",
      href: "https://pascalgaming.com/games/fortune-pots",
    },
    intro: "“Fortune Pots” is an Asian-themed mobile slot game featuring a 5x3 reel grid, four progressive jackpot tiers (Grand, Major, Minor, Mini), and three dynamic pot-collection bonus features (“EXTRA”, “DOUBLE”, and “MULTI”). The game combines traditional slot gameplay with a direct “Buy Bonus” option and visual collection mechanics.",
    problem: "<p>Asian-style jackpot slot games with multiple pot-collection mechanics often struggle with visual clutter, especially on portrait mobile screens. The challenge was to keep the top jackpot displays and pot triggers instantly clear while building a standardized, touch-friendly betting dock and modal system that can scale seamlessly across similar slot titles.</p>",
    contribution: "<p>I designed the complete UI/UX framework for the betting interface, control buttons, jackpot HUDs, popup modal systems, and all visual multipliers (excluding the individual reel game symbols). Notably, this betting layout was built as a core reusable architecture utilized across similar bonus-heavy slot games in our product portfolio. Key highlights include:</p><ul><li><strong>Core Reusable Betting Dock</strong> Engineered the mobile-optimized bottom control system—including the main spin button, bet level adjusters (- / +), last win tracker, and quick-action toggles (Turbo, Auto-spin)—as a core UI module applied across similar slot titles.</li><li><strong>Jackpot &amp; Pot Feature HUD</strong> Designed high-contrast jackpot badges (Grand, Major, Minor, Mini) and distinct pot labels (“EXTRA”, “DOUBLE”, “MULTI”) to maintain readability on mobile screens.</li><li><strong>Custom Buttons &amp; Bonus-Buy Access</strong> Designed themed CTA buttons, including the prominent “BUY BONUS” side button, ensuring consistent visual language and accidental-click prevention.</li><li><strong>Complete Multipliers &amp; Visual Assets</strong> Designed all multiplier UI elements, numeric badges, and popup indicators across the main game interface and bonus overlays to ensure crisp visual feedback during feature triggers.</li></ul>",
    validation: "<p>The design was reviewed with product stakeholders and validated through playtesting. Standardizing this core betting architecture across similar games reduced player learning curves when switching titles, while the high-visibility jackpot headers and “Buy Bonus” entry point led to increased player engagement and feature utilization.</p>",
  },
  {
    slug: "the-golden-egg",
    name: "The Golden Egg",
    category: "slots",
    platform: "online",
    company: "Pascal Gaming",
    role: "UX / UI",
    coverAlt: "The Golden Egg game artwork",
    desktopAlt: "The Golden Egg desktop design",
    mobileAlt: "The Golden Egg mobile design",
    link: {
      kind: "play",
      href: "https://pascalgaming.com/games/the-golden-egg",
    },
    intro: "“The Golden Egg” is a countryside-themed video slot game featuring sticky Wild multipliers, scatter-triggered free spin bonus rounds, card-suit progressive jackpots, and an instant “Buy Bonus” feature allowing players to directly trigger high-volatility free spin rounds.",
    problem: "<p>Desktop and mobile slot games require an ergonomic, highly clear betting UI and modal workflow that can function seamlessly across an entire suite of slot titles without re-engineering core controls for every new release. The challenge was to design a mobile and web-responsive betting architecture—including complex popup interfaces like Bonus Buy options, multiplier badges, and win celebrations—that ensures high visual clarity, simple navigation, and brand consistency across diverse game themes.</p>",
    contribution: "<p>I designed the complete UI/UX framework for the betting interface, control buttons, jackpot HUDs, popup modal systems, and all visual multipliers (excluding the individual reel game symbols). Notably, this betting architecture was engineered as a core reusable architecture utilized across similar slot games in our product portfolio. Key highlights include:</p><ul><li><strong>Core Reusable Betting Dock</strong> Engineered the main control bar—including the primary spin button, direct stake adjusters (- / +), bet amount readout, last-win tracker, balance display, and quick-action toggles (Turbo, Auto-spin, drawer settings)—as a standardized core component reused across similar slot titles.</li><li><strong>Themed “Buy Bonus” Access &amp; Modals</strong> Created the integrated “BUY BONUS” side button with live cost calculation alongside the full popup overlay system for feature purchases.</li><li><strong>Card-Suit Jackpot HUD</strong> Structured the top card-suit progressive jackpot counters (Clubs, Diamonds, Hearts, Spades) to deliver clear, high-contrast real-time reward updates.</li><li><strong>Complete Multiplier &amp; UI Element Design</strong> Designed all multiplier UI badges, numeric indicators, buttons, and popup dialogs across the game, maintaining crisp visual hierarchy and immediate player feedback during feature triggers.</li></ul>",
    validation: "<p>The framework was reviewed with product stakeholders and deployed across multiple slot titles. Standardizing this core betting engine across similar games drastically reduced development deployment time, while the intuitive breakdown of feature cards and explicit multiplier controls resulted in higher feature adoption and smoother overall session flow.</p>",
  },
  {
    slug: "book-of-the-sun",
    name: "Book Of The Sun",
    category: "slots",
    platform: "online",
    company: "Pascal Gaming",
    role: "UX / UI",
    coverAlt: "Book Of The Sun game artwork",
    desktopAlt: "Book Of The Sun desktop design",
    mobileAlt: "Book Of The Sun mobile design",
    link: {
      kind: "play",
      href: "https://pascalgaming.com/games/book-of-the-sun",
    },
    intro: "“Book of the Sun” is an Ancient Egyptian-themed video slot game built around iconic “Book of...” slot mechanics. It features expanding symbols during free spin bonus rounds, scatter/wild combinations, card-suit progressive jackpots, and an instant “Buy Bonus” feature allowing players to directly purchase bonus rounds.",
    problem: "<p>Theme-driven slot games require an ergonomic, standardized betting UI and modal workflow that can function seamlessly across an entire portfolio without re-engineering core controls for every new title release. The challenge was to design a mobile- and web-responsive betting architecture—including complex popup interfaces, multiplier badges, and feature buy overlays—that ensures high visual clarity, one-handed usability, and brand consistency across diverse game themes.</p>",
    contribution: "<p>I designed the complete UI/UX framework for the betting interface, control buttons, jackpot HUDs, popup modal systems, and all visual multipliers (excluding the individual reel game symbols). Notably, this betting architecture was engineered as a core reusable component utilized across similar slot games in our product portfolio. Key highlights include:</p><ul><li><strong>Core Reusable Betting Dock</strong> Engineered the main control bar—including the primary spin button, direct stake adjusters (- / +), bet amount readout, last-win tracker, balance display, and quick-action toggles (Turbo, Auto-spin, settings drawer)—as a standardized core component reused across similar slot titles.</li><li><strong>Themed “Buy Bonus” Access &amp; Modals</strong> Created the integrated “BUY BONUS” side button with live cost calculation alongside the full popup overlay system for feature purchases and bonus round confirmations.</li><li><strong>Progressive Jackpot HUD</strong> Structured the top progressive jackpot counters to deliver clear, high-contrast real-time reward updates without distracting from the Egyptian-themed reel area.</li><li><strong>Complete Multiplier &amp; UI Element Design</strong> Designed all multiplier UI badges, numeric indicators, buttons, and popup dialogs across the game, maintaining crisp visual hierarchy and immediate player feedback during feature triggers and expanding symbol wins.</li></ul>",
    validation: "<p>The framework was reviewed with product stakeholders and deployed across multiple slot titles. Standardizing this core betting engine across similar games drastically reduced development deployment time, while the intuitive breakdown of feature cards and explicit multiplier controls resulted in higher feature adoption and smoother overall session flow.</p>",
  },
  {
    slug: "golden-keno",
    name: "Golden Keno",
    category: "betshop",
    platform: "retail",
    company: "Pascal Gaming",
    role: "UX / UI",
    coverAlt: "Golden Keno game artwork",
    desktopAlt: "Golden Keno betshop broadcast design",
    mobile: false,
    link: {
      kind: "play",
      href: "https://pascalgaming.com/game-portfolio",
    },
    intro: "“Golden Keno 80” is a premium 80-ball retail Keno game crafted for overhead betshop broadcast displays. Wrapped in a luxury gold-and-black aesthetic, the game features continuous fast draws, real-time ball reveals, progressive jackpot tracking (Mini, Major, and Grand), and a live draw history line for retail bettors.",
    problem: "<p>In a noisy, crowded betshop environment, standard Keno broadcast screens often struggle to maintain visual elegance while keeping draw information clear. The interface needed to deliver high-end visual appeal while ensuring that live ball reveals and drawn-number highlights remain instantly readable from any distance or viewing angle across the venue.</p>",
    contribution: "<p>I designed the complete TV broadcast UI/UX for “Golden Keno 80,” focusing on far-field visibility and a high-contrast luxury aesthetic.</p>",
    validation: "<p>The interface was reviewed with retail operators and tested on in-shop TV monitors. The bold, far-field clarity of the central reveal ring combined with the high-contrast gold grid highlights allowed shop customers to easily track live draws from anywhere in the venue, resulting in higher draw retention and faster round-to-round ticket verification.</p>",
  },
  {
    slug: "spin-to-win-lightning",
    name: "Spin To Win Lightning",
    category: "betshop",
    platform: "retail",
    company: "Pascal Gaming",
    role: "UX / UI",
    coverAlt: "Spin To Win Lightning game artwork",
    desktopAlt: "Spin To Win Lightning betshop broadcast design",
    mobile: false,
    link: {
      kind: "play",
      href: "https://pascalgaming.com/game-portfolio",
    },
    intro: "“Spin &amp; Win Lightning” is a fast-paced, roulette-inspired retail betshop game centered around a multi-ring wheel featuring numbers (0–36) and inner sector divisions (A– F). Before each spin, random numbers are hit by “Lightning Multipliers” (up to x500 or more), offering boosted payouts. Players can place bets on individual numbers, colors, sectors, dozens, or even/odd outcomes while competing for three progressive jackpots (Mini, Major, and Grand).",
    problem: "<p>Games designed for retail betshop environments face a unique UX challenge: information must be instantly readable from a distance on overhead TV screens. The interface needed to display deep statistical data, pay tables, active jackpot tiers, countdown timers, and high-impact “lightning” multiplier callouts simultaneously on a single broadcast layout without creating visual noise or confusing players placing tickets at the counter.</p>",
    contribution: "<p>I designed the complete TV broadcast UI for “Spin &amp; Win Lightning,” specifically optimized for retail betshop displays and terminal synchronization.</p>",
    validation: "<p>The design was reviewed with retail product stakeholders and tested on in-shop displays. Betshop operators noted that the far-field clarity of the statistics panel and prominent lightning multipliers allowed customers to make quick betting decisions from anywhere in the venue, leading to faster bet processing at cashiers and higher draw-to-draw engagement.</p>",
  },
  {
    slug: "greyhound-racing",
    name: "Greyhound Racing",
    category: "betshop",
    platform: "retail",
    company: "Pascal Gaming",
    role: "UX / UI",
    coverAlt: "Greyhound Racing game artwork",
    desktopAlt: "Greyhound Racing betshop broadcast design",
    mobile: false,
    link: {
      kind: "play",
      href: "https://pascalgaming.com/game-portfolio",
    },
    intro: "“Greyhound Racing” is a virtual sports betting game built for retail betshop broadcast displays and terminal screens. It features fast-paced virtual greyhound races backed by comprehensive betting markets—including Win/Place/Show, Exacta (Forecast Straight), Quinella (Forecast Reverse), Over/Under, Even/Odd, and past race forms—alongside progressive jackpot integration.",
    problem: "<p>Virtual racing screens in retail environments face a significant data-density challenge: they must present a vast amount of statistical information and complex market odds (runner ratings, past form, 6x6 forecast matrices, and side bets) on a single screen. The goal was to construct a highly structured, far-field readable layout that allows betshop players to digest dozens of live odds and place multi-market tickets before the race countdown expires.</p>",
    contribution: "<p>I designed the complete TV broadcast UI/UX for “Greyhound Racing,” focusing on data visual architecture, market hierarchy, and far-field readability.</p>",
    validation: "<p>The interface was reviewed with retail operators and tested on in-shop TV monitors. The bold, far-field clarity of the central reveal ring combined with the high-contrast gold grid highlights allowed shop customers to easily track live draws from anywhere in the venue, resulting in higher draw retention and faster round-to-round ticket verification.</p>",
  },
  {
    slug: "sportcore",
    name: "Sportcore",
    category: "sportsbook",
    platform: "web",
    company: "Sportcore",
    role: "UX / UI",
    coverAlt: "Sportcore sportsbook and casino interface",
    desktopAlt: "Sportcore full interface design",
    mobile: false,
    link: {
      kind: "figma",
      href: "https://www.figma.com/design/U80w2jt7nh5syyxM4g1Dtc/Sportcore?node-id=1-25075",
    },
    summary: {
      en: "Sportsbook and casino interfaces designed from scratch.",
      hy: "Զրոյից նախագծված սպորտային խաղադրույքների և կազինոյի ինտերֆեյսներ։",
      ru: "Интерфейсы спортивных ставок и казино, созданные с нуля.",
    },
    intro: "“Sportcore” is an enterprise-grade web sportsbook and iGaming portal designed for high-volume betting markets. The platform integrates real-time sports odds, live match broadcasts, virtual sports, mini-games, live dealer casino suites, and multi-provider slot libraries into a single unified desktop ecosystem featuring advanced account management utilities.",
    problem: "<p>High-traffic betting platforms serving both sports bettors and casino players face severe layout density challenges. Displaying complex odds tables, live head-to-head match stats, dual balance structures (Sports vs. Casino funds), and instant ticket calculations on a single screen often leads to visual overload, making rapid decision-making difficult during live events.</p>",
    contribution: "<p>I designed the complete desktop UI/UX architecture and dark-mode design system for the platform, focusing on structural layout, quick data scanning, and seamless multi-vertical navigation. Key highlights include:</p><ul><li><strong>Integrated User Profile &amp; Dual-Balance Betslip (Right)</strong> Structured a dedicated right sidebar uniting real-time account management (separating Sport and Casino balances with quick deposit/withdrawal tools) directly above a persistent betslip featuring quick-stake preset buttons ($5,000 to $30,000), system bet tab controls, and payout calculations.</li><li><strong>Data-Dense Sportsbook &amp; Match Center (Center)</strong> Engineered a clean multi-column sports dashboard featuring quick-filter sport icon ribbons, expandable league accordions (K League, Serie A, Bundesliga), and an integrated visual H2H match module for live tactical analysis.</li><li><strong>Immersive Casino &amp; Live Dealer Hub</strong> Designed a structured iGaming layout featuring a prominent promotional hero carousel (“Winning Ways”), sub-category filters (Main, Live Casino, Featured Slots, Providers), and high-contrast thumbnail grids optimized for rapid game discovery.</li><li><strong>Comprehensive Utility Navigation</strong> Built a consolidated left sidebar grouping core account functions (Attendance rewards, Money Transfer, Cash History, Friend Recommendations) alongside quick league shortcuts for rapid platform navigation.</li></ul>",
    validation: "<p>The interface system was reviewed with product stakeholders and usability-tested with active bettors. The unified account panel and structured market grids significantly reduced friction when placing live multi-bets, while the visual distinction between sportsbook and casino modules enabled faster navigation and improved overall user retention across both verticals.</p>",
  },
  {
    slug: "tether-bet",
    name: "Tether Bet",
    category: "sportsbook",
    platform: "web",
    company: "Tether Bet",
    role: "UX / UI",
    coverAlt: "Tether Bet sportsbook and casino interface",
    desktopAlt: "Tether Bet full interface design",
    mobile: false,
    link: {
      kind: "figma",
      href: "https://www.figma.com/design/aZdK37QgjWvJwalRFOJ1MK/Tether-Bet?node-id=8-25822",
    },
    summary: {
      en: "Sportsbook and casino interfaces designed from scratch.",
      hy: "Զրոյից նախագծված սպորտային խաղադրույքների և կազինոյի ինտերֆեյսներ։",
      ru: "Интерфейсы спортивных ставок и казино, созданные с нуля.",
    },
    intro: "“tether.bet” is a modern crypto sportsbook and iGaming platform designed to deliver a unified, high-performance betting experience. The web platform combines live sports betting, prematch markets, an extensive casino game lobby, live dealer tables, and crypto wallet management within a seamless, single-page application structure.",
    problem: "<p>Dual-purpose platforms (sportsbook + casino) often suffer from overwhelming visual noise, fragmented navigation, and disjointed user flows. Switching between complex sports odds, live event feeds, multi-provider slot catalogs, and an active betslip without losing state context or cluttering the screen presents a significant UX layout challenge.</p>",
    contribution: "<p>I designed the end-to-end UI/UX architecture for the tether.bet web application, creating a cohesive visual system across both the Sportsbook and Casino verticals. Key highlights include:</p><ul><li><strong>Unified Header &amp; Product Switcher</strong> Designed a clean top navigation bar with one-click mode switching (Sports / Casino), integrated crypto wallet management (Wallet button), balance readouts, and global account quick-actions.</li><li><strong>Modular Sportsbook Layout</strong> Structured a multi-column sports interface featuring a collapsible left sidebar for sports/leagues, dynamic promo card carousels, live match odds grids (1x2), and quick category filters (Football, Basketball, Esports, etc.).</li><li><strong>Dynamic Casino &amp; Provider Lobby</strong> Designed an intuitive casino discovery interface featuring rich game grid cards, category tabs (Top Games, Slots, Tether Originals), promotional banner carousels, and visual game provider filters (NetEnt, Hacksaw, Evoplay, etc.).</li><li><strong>Persistent Universal Betslip</strong> Created an integrated right-side Betslip container supporting Single, System, and Chain bet types, allowing players to build tickets, manage stakes, and place bets continuously across both sports and casino pages.</li><li><strong>High-Contrast Dark Visual System</strong> Developed a clean dark-mode UI with high-visibility emerald green accents, structured typography, and minimalist iconography to reduce eye strain during extended gaming sessions.</li></ul>",
    validation: "<p>The UI/UX design system was reviewed with product stakeholders and validated through usability testing with sports bettors and casino players. The unified architecture and persistent betslip drastically reduced friction when navigating between live sports and casino games, leading to higher cross-product conversion, faster bet execution times, and improved platform session retention.</p>",
  },
];
